version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      # Allow updates for 
      - dependency-name: "@sentry/react"
      - dependency-name: "@sentry/tracing"
      - dependency-name: "@tauri-apps/api" 
      - dependency-name: "@crowdin/cli" 
      - dependency-name: "@tauri-apps/cli"
    assignees:
      - "andrewstech"
     

# Dummy commit needed to enable Dependabot
