project_id: '506638'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /public/locales/en/translate.json
    translation: /public/locales/%two_letters_code%/%original_file_name%
