name: Generate PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: win11bot/preview

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM packages
        run: npm ci

      - name: Get translations
        run: npm run crowdin download
        env:
          api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build project
        run: CI=false PUBLIC_URL=https://preview.pr.blueedge.me/pr-${{ github.event.pull_request.number }} npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          destination_dir: ./${{ github.event.pull_request.number }}
          cname: preview.pr.blueedge.me
          external_repository: win11bot/preview

      - name: Sleep for 60 seconds to make sure page updated
        uses: jakejarvis/wait-action@master
        with:
          time: "60s"

      - name: pr
        uses: mshick/add-pr-comment@v1
        env:
          BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.BOT }}
        with:
          message: |
            ✔️ Deploy Preview for Ready!
            😎 Browse the preview: https://preview.pr.blueedge.me/pr-${{ github.event.pull_request.number }} !
            🔍 Inspect the deploy log: ${{ env.BUILD_URL }}
                Feel free to join our github org. Click [here](https://github.com/win11react/members/issues/new?assignees=&labels=join&template=join.md&title=I+want+to+join+the+org)
          allow-repeats: true

  run-if-fail:
    if: ${{ always() && (needs.Build.result=='failure') }}
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: ❌ DEPLOY PREVIEW HAS FAILED
          repo-token: ${{ secrets.BOT }}
          allow-repeats: true
