name: issue-text

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hey, thank you for creating an issue. We will normally respond within 24 hours."
        GITHUB_TOKEN: ${{ secrets.BOT }}
        
    - uses: stefanbuck/github-issue-parser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/bug_report.yml
        
    - run: echo '${{ steps.issue-parser.outputs.jsonString }}    
        
