name: Delete PR Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  Close:
    runs-on: ubuntu-latest

    steps:
      - name: delete repo
        run: gh repo delete win11bot/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
